source "https://rubygems.org"

ruby "4.0.6"

gem "dry-initializer", "~> 3.2"
gem "dry-monads", "~> 1.6"
gem "dry-struct", "~> 1.6"
gem "dry-validation", "~> 1.10"

group :development, :test do
  gem "rspec", "~> 3.13"
  gem "rubocop", "~> 1.75", require: false
end
